### ISSUE TITLE
Issues compiling with GCC 5.4.0

### ISSUE THREAD

**Issue by platinum95** [peadar/pstack#1]
Was running into some C++14 related issues when compiling with gcc 5.4.0. Seems like `-std=c++14` wasn't getting set during the cmake configuration. 
Got around the problem by adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")` to the 2 CMakeLists. 
Not sure if this affects any other versions (haven't checked) or if it's even a real issue, just figured I'd post.

**Comment by peadar** [comment]
Can you tell me what version of cmake you're using? Is this a stock Linux
distro? If so, which and which version?

**Comment by platinum95** [comment]
Closing since issue was due to cmake 2.8, which was released prior to widespread c++14 support.
