### ISSUE TITLE
Argument printing for C++ pass by reference

### ISSUE THREAD

**Issue by jimmychang851129** [peadar/pstack#22]
Hi, thanks a lot for the amazing work. This is really useful and help a lot for our projects. 

We encounter an issue regarding argument printing.

Can the pstack also print function argument that are passed by reference?

As we only see the memory address for "pass by reference" argument instead of its value.

**Comment by peadar** [comment]
Should be fixed by d9dd47bcaea5befa5c1e2de34d0f778412901618

**Comment by peadar** [comment]
fixed in
d9dd47bcaea5befa5c1e2de34d0f778412901618
