### ISSUE TITLE
git clone on Windows 11 fails

### ISSUE THREAD

**Issue by kirtivr** [peadar/pstack#26]
Hi Peter!

It has been a while since we last connected during my internship at Arista (2017.. I used the DWARF goodness of pstack for some work). Hope all is well! :)

I have been doing some work with your code on Linux, and happened to clone the repository on Windows recently.

However, the clone failed:
![clone_fails](https://github.com/user-attachments/assets/6ba4200f-ed2a-4baa-bb67-bcbd1a91489a)

While doing an investigation as to why, I found out it is one of those Windows quirks where you cannot have files that have certain names (like "conn" and "aux").

![image](https://github.com/user-attachments/assets/3a3e97cd-5a30-4956-97c5-d9648d0b0852)

Windows does not like the file at this [path](https://github.com/peadar/pstack/blob/master/libpstack/elf/aux.h) because it has the name 
"aux.h". Stackoverflow answer explaining [workarounds](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows).

Note that the workarounds did not work for me on Windows 11. My workaround was to rename "aux.h" to "aux_.h"

I'm not sure you even want to fix this since "pstack" is not meant to be used on Windows, but I thought I'd pass the word along.

Best,
Kirti

**Comment by peadar** [comment]
Thanks for the report, and hope you're doing well - good to hear from you.

I can't do a whole lot about the history, and you'll have problems checking out any earlier commits, but I've renamed aux.h to auxv.h - there's no harm in fixing things so you can check it out on windows, even if it doesn't compile. "auxv" is probably a better name anyway, tbh.

**Comment by kirtivr** [comment]
Great, thanks for the fix!
